CREATE INDEX INST_ZIP_FK_I ON INSTRUCTOR
 (ZIP);

CREATE INDEX GR_GRTW_FK_I ON GRADE
 (SECTION_ID
 ,GRADE_TYPE_CODE);

CREATE INDEX GRTW_GRTYP_FK_I ON GRADE_TYPE_WEIGHT
 (GRADE_TYPE_CODE);

CREATE INDEX SECT_CRSE_FK_I ON SECTION
 (COURSE_NO);

CREATE INDEX SECT_INST_FK_I ON SECTION
 (INSTRUCTOR_ID);

CREATE INDEX CRSE_CRSE_FK_I ON COURSE
 (PREREQUISITE);

CREATE INDEX ENR_SECT_FK_I ON ENROLLMENT
 (SECTION_ID);

CREATE INDEX STU_ZIP_FK_I ON STUDENT
 (ZIP);