ALTER TABLE INSTRUCTOR
 MODIFY(MODIFIED_BY CONSTRAINT INST_MODFIED_BY_NNULL NOT NULL)
 MODIFY(INSTRUCTOR_ID CONSTRAINT INST_INSTRUCTOR_ID_NNULL NOT NULL)
 MODIFY(CREATED_BY CONSTRAINT INST_CREATED_BY_NNULL NOT NULL)
 MODIFY(CREATED_DATE CONSTRAINT INST_CREATED_DATE_NNULL NOT NULL)
 MODIFY(MODIFIED_DATE CONSTRAINT INST_MODIFIED_DATE_NNULL NOT NULL)
;

ALTER TABLE GRADE
 MODIFY(CREATED_DATE CONSTRAINT GR_CREATED_DATE_NNULL NOT NULL)
 MODIFY(STUDENT_ID CONSTRAINT GR_STUDENT_ID_NNULL NOT NULL)
 MODIFY(SECTION_ID CONSTRAINT GR_SECTION_ID_NNULL NOT NULL)
 MODIFY(GRADE_TYPE_CODE CONSTRAINT GR_GRADE_TYPE_CODE_NNULL NOT NULL)
 MODIFY(MODIFIED_DATE CONSTRAINT GR_MODIFIED_DATE_NNULL NOT NULL)
 MODIFY(CREATED_BY CONSTRAINT GR_CREATED_BY_NNULL NOT NULL)
 MODIFY(GRADE_CODE_OCCURRENCE CONSTRAINT GR_GRADE_CODE_OCCURRENCE_NNULL NOT NULL)
 MODIFY(MODIFIED_BY CONSTRAINT GR_MODIFIED_BY_NNULL NOT NULL)
 MODIFY(NUMERIC_GRADE CONSTRAINT GR_NUMERIC_GRADE_NNULL NOT NULL)
;

ALTER TABLE GRADE_TYPE
 MODIFY(DESCRIPTION CONSTRAINT GRTYP_DESCRIPTION_NNULL NOT NULL)
 MODIFY(MODIFIED_BY CONSTRAINT GRTYP_MODIFIED_BY_NNULL NOT NULL)
 MODIFY(CREATED_BY CONSTRAINT GRTYP_CREATED_BY_NNULL NOT NULL)
 MODIFY(GRADE_TYPE_CODE CONSTRAINT GRTYP_GRADE_TYPE_CODE_NNULL NOT NULL)
 MODIFY(MODIFIED_DATE CONSTRAINT GRTYP_MODIFIED_DATE_NNULL NOT NULL)
 MODIFY(CREATED_DATE CONSTRAINT GRTYP_CREATED_DATE_NNULL NOT NULL)
 ADD CONSTRAINT GRTYP_GRADE_TYPE_CODE_LENGTH CHECK (LENGTH(grade_type_code)=2)
;
 
ALTER TABLE GRADE_CONVERSION
 MODIFY(MAX_GRADE CONSTRAINT GRCON_MAX_GRADE_NNULL NOT NULL)
 MODIFY(MODIFIED_DATE CONSTRAINT GRCON_MODIFIED_DATE_NNULL NOT NULL)
 MODIFY(CREATED_DATE CONSTRAINT GRCON_CREATED_DATE_NNULL NOT NULL)
 MODIFY(GRADE_POINT CONSTRAINT GRCON_GRADE_POINT_NNULL NOT NULL)
 MODIFY(MODIFIED_BY CONSTRAINT GRCON_MODIFIED_BY_NNULL NOT NULL)
 MODIFY(LETTER_GRADE CONSTRAINT GRCON_LETTER_GRADE_NNULL NOT NULL)
 MODIFY(MIN_GRADE CONSTRAINT GRCON_MIN_GRADE_NNULL NOT NULL)
 MODIFY(CREATED_BY CONSTRAINT GRCON_CREATED_BY_NNULL NOT NULL)
;
 
ALTER TABLE GRADE_TYPE_WEIGHT
 MODIFY(NUMBER_PER_SECTION CONSTRAINT GRTW_NUMBER_PER_SECTION_NNULL NOT NULL)
 MODIFY(CREATED_DATE CONSTRAINT GRTW_CREATED_DATE_NNULL NOT NULL)
 MODIFY(PERCENT_OF_FINAL_GRADE CONSTRAINT GRTW_PCT_OF_FINAL_GRADE_NNULL NOT NULL)
 MODIFY(GRADE_TYPE_CODE CONSTRAINT GRTW_GRADE_TYPE_CODE_NNULL NOT NULL)
 MODIFY(SECTION_ID CONSTRAINT GRTW_SECTION_ID_NNULL NOT NULL)
 MODIFY(MODIFIED_BY CONSTRAINT GRTW_MODIFIED_BY_NNULL NOT NULL)
 MODIFY(CREATED_BY CONSTRAINT GRTW_CREATED_BY_NNULL NOT NULL)
 MODIFY(DROP_LOWEST CONSTRAINT GRTW_DROP_LOWEST_NNULL NOT NULL)
 MODIFY(MODIFIED_DATE CONSTRAINT GRTW_MODIFIED_DATE_NNULL NOT NULL)
;
 
ALTER TABLE SECTION
 MODIFY(CREATED_DATE CONSTRAINT SECT_CREATED_DATE_NNULL NOT NULL)
 MODIFY(MODIFIED_BY CONSTRAINT SECT_MODIFIED_BY_NNULL NOT NULL)
 MODIFY(SECTION_ID CONSTRAINT SECT_SECTION_ID_NNULL NOT NULL)
 MODIFY(SECTION_NO CONSTRAINT SECT_SECTION_NO_NNULL NOT NULL)
 MODIFY(CREATED_BY CONSTRAINT SECT_CREATED_BY_NNULL NOT NULL)
 MODIFY(INSTRUCTOR_ID CONSTRAINT SECT_INSTRUCTOR_ID_NNULL NOT NULL)
 MODIFY(MODIFIED_DATE CONSTRAINT SECT_MODIFIED_DATE_NNULL NOT NULL)
 MODIFY(COURSE_NO CONSTRAINT SECT_COURSE_NO_NNULL NOT NULL)
;
 
ALTER TABLE COURSE
 MODIFY(CREATED_DATE CONSTRAINT CRSE_CREATED_DATE_NNULL NOT NULL)
 MODIFY(MODIFIED_BY CONSTRAINT CRSE_MODIFIED_BY_NNULL NOT NULL)
 MODIFY(MODIFIED_DATE CONSTRAINT CRSE_MODIFIED_DATE_NNULL NOT NULL)
 MODIFY(DESCRIPTION CONSTRAINT CRSE_DESCRIPTION_NNULL NOT NULL)
 MODIFY(COURSE_NO CONSTRAINT CRSE_COURSE_NO_NNULL NOT NULL)
 MODIFY(CREATED_BY CONSTRAINT CRSE_CREATED_BY_NNULL NOT NULL)
;
 
ALTER TABLE ENROLLMENT
 MODIFY(MODIFIED_DATE CONSTRAINT ENR_MODIFIED_DATE_NNULL NOT NULL)
 MODIFY(STUDENT_ID CONSTRAINT ENR_STUDENT_ID_NNULL NOT NULL)
 MODIFY(ENROLL_DATE CONSTRAINT ENR_ENROLL_DATE_NNULL NOT NULL)
 MODIFY(MODIFIED_BY CONSTRAINT ENR_MODIFIED_BY_NNULL NOT NULL)
 MODIFY(SECTION_ID CONSTRAINT ENR_SECTION_ID_NNULL NOT NULL)
 MODIFY(CREATED_BY CONSTRAINT ENR_CREATED_BY_NNULL NOT NULL)
 MODIFY(CREATED_DATE CONSTRAINT ENR_CREATED_DATE_NNULL NOT NULL)
;
 
ALTER TABLE STUDENT
 MODIFY(REGISTRATION_DATE CONSTRAINT STU_REGISTRATION_DATE_NNULL NOT NULL)
 MODIFY(CREATED_BY CONSTRAINT STU_CREATED_BY_NNULL NOT NULL)
 MODIFY(ZIP CONSTRAINT STU_ZIP_NNULL NOT NULL)
 MODIFY(LAST_NAME CONSTRAINT STU_LAST_NAME_NNULL NOT NULL)
 MODIFY(MODIFIED_DATE CONSTRAINT STU_MODIFIED_DATE_NNULL NOT NULL)
 MODIFY(STUDENT_ID CONSTRAINT STU_STUDENT_ID_NNULL NOT NULL)
 MODIFY(MODIFIED_BY CONSTRAINT STU_MODIFIED_BY_NNULL NOT NULL)
 MODIFY(CREATED_DATE CONSTRAINT STU_CREATED_DATE_NNULL NOT NULL)
;
 
ALTER TABLE ZIPCODE
 MODIFY(CREATED_BY CONSTRAINT ZIP_CREATED_BY_NNULL NOT NULL)
 MODIFY(MODIFIED_DATE CONSTRAINT ZIP_MODIFIED_DATE_NNULL NOT NULL)
 MODIFY(CREATED_DATE CONSTRAINT ZIP_CREATED_DATE_NNULL NOT NULL)
 MODIFY(ZIP CONSTRAINT ZIP_ZIP_NNULL NOT NULL)
 MODIFY(MODIFIED_BY CONSTRAINT ZIP_MODIFIED_BY_NNULL NOT NULL)
;